server:
  port: 6746

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orion
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      initial-size: 1
      min-idle: 1
      max-idle: 20
      max-active: 20
      max-wait: 60000

logging:
  level: trace

mybatis:
  type-aliases-package: com.lookcc.orion.model
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count\=countSql

mapper:
  mappers: com.lookcc.orion.common.BaseMapper
  not-empty: false
  identity: MYSQL
